package info.xiancloud.dao.core.model.sqlresult;

/**
 * Single record insertion result bean
 *
 * @author happyyangyuan
 */
public class SingleInsertionResult implements SqlExecutionResult {
    /**
     * id value generated by database when insertion
     */
    private Number id;
    /**
     * succeeded insertion count
     */
    private int count;

    /**
     * the prepared sql
     */
    private String preparedSql;

    public Number getId() {
        return id;
    }

    public SingleInsertionResult setId(Number id) {
        this.id = id;
        return this;
    }

    public int getCount() {
        return count;
    }

    public SingleInsertionResult setCount(int count) {
        this.count = count;
        return this;
    }

    public String getPreparedSql() {
        return preparedSql;
    }

    public SingleInsertionResult setPreparedSql(String preparedSql) {
        this.preparedSql = preparedSql;
        return this;
    }
}
